/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#fdf8f8',
        'on-background': '#1c1b1b',
        surface: '#fdf8f8',
        'on-surface': '#1c1b1b',
        primary: '#001184',
        'on-primary': '#ffffff',
        'primary-container': '#001ec0',
        'on-primary-container': '#96a1ff',
        secondary: '#5e5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1dfdf',
        'on-secondary-container': '#636262',
        tertiary: '#262826',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#3c3e3c',
        'on-tertiary-container': '#a8a9a6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f2f2',
        'surface-container': '#f1edec',
        'surface-container-high': '#ece7e7',
        'surface-container-highest': '#e6e1e1',
        'surface-variant': '#e6e1e1',
        'on-surface-variant': '#454655',
        outline: '#757687',
        'outline-variant': '#c5c5d8',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#172dc8',
        'on-secondary-fixed-variant': '#464747',
        'on-tertiary-fixed-variant': '#454745',
      },
      fontFamily: {
        sans: ['Jost', 'sans-serif'],
      },
      spacing: {
        'margin-desktop': '64px',
        'unit': '8px',
        'section-gap': '128px',
        'gutter': '24px',
        'margin-mobile': '20px',
        'container-max': '1440px',
      },
      fontSize: {
        display: ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        'headline-lg': ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        'headline-lg-mobile': ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        'headline-md': ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        'body-lg': ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        'body-md': ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        button: ["14px", { lineHeight: "1.0", letterSpacing: "0.02em", fontWeight: "600" }],
        'label-caps': ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
